# Generated by Django 2.2.7 on 2019-11-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
